# Generated by Django 5.2.6 on 2025-09-14 10:45

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resume_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=200)),
                (
                    'phone_number',
                    models.CharField(blank=True, default='', max_length=20),
                ),
                (
                    'resume',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='personal_info',
                        to='resume_builder.resume',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
