# Generated by Django 5.2.6 on 2025-09-16 06:39

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resume_builder', '0002_personalinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                (
                    'resume',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='education_records',
                        to='resume_builder.resume',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
